# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c68d89b2bc07603fcb7919c6bec32f055397a3e806996baec54d4de57162d68333cea465cfd683275cc68b353d15c7406eceb7dfd408b0590c0181cce6e34e32

test:
  secret_key_base: 6cd9d6a78301447f410acc54951c563929b80abcffe15a18d4dc1ef83a9489822ad06174e0b553cdf86e6f635d9d584128d25c533a6e5965fd1eaf638dcb6e98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
